arch:
    max_epochs: 20
model:
    name: 'SelfSupModelDepth'
    loss:
        upsample_depth_maps: False
        ssim_loss_weight : 0.5
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.00003
        pose:
            lr: 0.00003
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNet01'
        version: 'TA'
        #checkpoint_path: '/home/sj/src/packnet-sfm/result/default_config-overfit_custom-2021.01.15-02h00m52s_test5/epoch=03_custom-val_files-loss=0.000.ckpt'
        checkpoint_path: '/home/sj/src/packnet-sfm/result/default_config-overfit_custom-2021.01.29-16h50m53s/epoch=09_custom-val_files-loss=0.000.ckpt'
    depth_net2:
        name: 'PackNet01'
        version: 'TA'        
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        min_depth: 1.0
        max_depth: 255.0
datasets:
    augmentation:
        image_shape: (256, 256)
    train:
        batch_size: 8
        dataset: ['Custom']
        path: ['data/datasets/custom']
        split: ['train_files.txt']
        depth_type: ['']
        repeat: [1]
    validation:
        dataset: ['Custom']
        path: ['data/datasets/custom']
        split: ['val_files.txt']
        depth_type: ['']
    test:
        dataset: ['Custom']
        path: ['data/datasets/custom']
        split: ['val_files.txt']
        depth_type: ['']
