arch:
    max_epochs: 20
model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.00003
        pose:
            lr: 0.00003
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNet01'
        version: 'TA'        
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        min_depth: 1.0
        max_depth: 255.0
datasets:
    augmentation:
        image_shape: (256, 256)
    train:
        batch_size: 4
        dataset: ['Custom']
        path: ['data/datasets/custom']
        split: ['train_files.txt']
        depth_type: ['']
        repeat: [1]
    validation:
        dataset: ['Custom']
        path: ['data/datasets/custom']
        split: ['val_files.txt']
        depth_type: ['']
    test:
        dataset: ['Custom']
        path: ['data/datasets/custom']
        split: ['val_files.txt']
        depth_type: ['']
