arch:
    max_epochs: 100
checkpoint:
    save_top_k: 5
    monitor : 'abs_rel_gt'
model:
    name: 'SelfSupModel'
    loss:
        upsample_depth_maps: True
    optimizer:
        name: 'AdamW'
        depth:
            lr: 0.00006
            betas: (0.9, 0.999)
            weight_decay: 0.01
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 10
        gamma: 0.9
    depth_net:
        name: 'DepthCMT2'
        embed_dim: 76
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    train:
        batch_size: 4
        dataset: ['KITTI']
        path: ['/home/sj/kitti']
        split: ['eigen_train_files.txt']
        depth_type: ['velodyne']
    validation:
        batch_size: 1
        dataset: ['KITTI']
        path: ['/home/sj/kitti']
        split: ['eigen_val_files.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['KITTI']
        path: ['/home/sj/kitti']
        split: ['eigen_test_files.txt']
        depth_type: ['velodyne']
