arch:
    max_epochs: 30
checkpoint:
    save_top_k: 5
    monitor : 'abs_rel_gt'
model:
    name: 'SelfSupModel'
    loss:
        upsample_depth_maps: True
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'DepthResNet'
        version: '18pt'    
        checkpoint_path: '/home/sj/src/packnet/result/default_config-overfit_custom_resnet18-2021.07.27-11h42m35s/epoch=00_custom-val_files-abs_rel_gt=0.223.ckpt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        min_depth: 1.0
        max_depth: 255.0
datasets:
    augmentation:
        image_shape: (256, 256)
    train:
        batch_size: 8
        dataset: ['Custom']
        path: ['/home/sj/src/packnet-sfm/data/datasets/custom']
        split: ['train_files.txt']
        depth_type: ['']
        repeat: [1]
    validation:
        batch_size: 8
        dataset: ['Custom']
        path: ['/home/sj/src/packnet-sfm/data/datasets/custom']
        split: ['val_files.txt']
        depth_type: ['']
    test:
        dataset: ['Custom']
        path: ['/home/sj/src/packnet-sfm/data/datasets/custom']
        split: ['val_files.txt']
        depth_type: ['']
