arch:
    max_epochs: 100
checkpoint:
    save_top_k: 5
    monitor : 'abs_rel_gt'
model:
    name: 'SelfSupModel'
    loss:
        upsample_depth_maps: True
    optimizer:
        name: 'AdamW'
        depth:
            lr: 0.00006
            betas: (0.9, 0.999)
            weight_decay: 0.01
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 10
        gamma: 0.5
    depth_net:
        name: 'DepthCMT'
        embed_dim: 46
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        min_depth: 1.0
        max_depth: 255.0
datasets:
    augmentation:
        image_shape: (256, 256)
    train:
        batch_size: 8
        dataset: ['Custom']
        path: ['/home/sj/src/packnet-sfm/data/datasets/custom']
        split: ['train_files.txt']
        depth_type: ['']
        repeat: [1]
    validation:
        batch_size: 1
        dataset: ['Custom']
        path: ['/home/sj/src/packnet-sfm/data/datasets/custom']
        split: ['val_files.txt']
        depth_type: ['']
    test:
        dataset: ['Custom']
        path: ['/home/sj/src/packnet-sfm/data/datasets/custom']
        split: ['val_files.txt']
        depth_type: ['']
